# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mmk07/Dropbox/Work/TSM/GPP/moldycat

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mmk07/Dropbox/Work/TSM/GPP/moldycat

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mmk07/Dropbox/Work/TSM/GPP/moldycat/CMakeFiles /home/mmk07/Dropbox/Work/TSM/GPP/moldycat/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mmk07/Dropbox/Work/TSM/GPP/moldycat/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named moldycat

# Build rule for target.
moldycat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 moldycat
.PHONY : moldycat

# fast build rule for target.
moldycat/fast:
	$(MAKE) -f CMakeFiles/moldycat.dir/build.make CMakeFiles/moldycat.dir/build
.PHONY : moldycat/fast

src/atom/atom.o: src/atom/atom.cpp.o
.PHONY : src/atom/atom.o

# target to build an object file
src/atom/atom.cpp.o:
	$(MAKE) -f CMakeFiles/moldycat.dir/build.make CMakeFiles/moldycat.dir/src/atom/atom.cpp.o
.PHONY : src/atom/atom.cpp.o

src/atom/atom.i: src/atom/atom.cpp.i
.PHONY : src/atom/atom.i

# target to preprocess a source file
src/atom/atom.cpp.i:
	$(MAKE) -f CMakeFiles/moldycat.dir/build.make CMakeFiles/moldycat.dir/src/atom/atom.cpp.i
.PHONY : src/atom/atom.cpp.i

src/atom/atom.s: src/atom/atom.cpp.s
.PHONY : src/atom/atom.s

# target to generate assembly for a file
src/atom/atom.cpp.s:
	$(MAKE) -f CMakeFiles/moldycat.dir/build.make CMakeFiles/moldycat.dir/src/atom/atom.cpp.s
.PHONY : src/atom/atom.cpp.s

src/atom/vect3.o: src/atom/vect3.cpp.o
.PHONY : src/atom/vect3.o

# target to build an object file
src/atom/vect3.cpp.o:
	$(MAKE) -f CMakeFiles/moldycat.dir/build.make CMakeFiles/moldycat.dir/src/atom/vect3.cpp.o
.PHONY : src/atom/vect3.cpp.o

src/atom/vect3.i: src/atom/vect3.cpp.i
.PHONY : src/atom/vect3.i

# target to preprocess a source file
src/atom/vect3.cpp.i:
	$(MAKE) -f CMakeFiles/moldycat.dir/build.make CMakeFiles/moldycat.dir/src/atom/vect3.cpp.i
.PHONY : src/atom/vect3.cpp.i

src/atom/vect3.s: src/atom/vect3.cpp.s
.PHONY : src/atom/vect3.s

# target to generate assembly for a file
src/atom/vect3.cpp.s:
	$(MAKE) -f CMakeFiles/moldycat.dir/build.make CMakeFiles/moldycat.dir/src/atom/vect3.cpp.s
.PHONY : src/atom/vect3.cpp.s

src/moldycat.o: src/moldycat.cpp.o
.PHONY : src/moldycat.o

# target to build an object file
src/moldycat.cpp.o:
	$(MAKE) -f CMakeFiles/moldycat.dir/build.make CMakeFiles/moldycat.dir/src/moldycat.cpp.o
.PHONY : src/moldycat.cpp.o

src/moldycat.i: src/moldycat.cpp.i
.PHONY : src/moldycat.i

# target to preprocess a source file
src/moldycat.cpp.i:
	$(MAKE) -f CMakeFiles/moldycat.dir/build.make CMakeFiles/moldycat.dir/src/moldycat.cpp.i
.PHONY : src/moldycat.cpp.i

src/moldycat.s: src/moldycat.cpp.s
.PHONY : src/moldycat.s

# target to generate assembly for a file
src/moldycat.cpp.s:
	$(MAKE) -f CMakeFiles/moldycat.dir/build.make CMakeFiles/moldycat.dir/src/moldycat.cpp.s
.PHONY : src/moldycat.cpp.s

src/sim/unitcell.o: src/sim/unitcell.cpp.o
.PHONY : src/sim/unitcell.o

# target to build an object file
src/sim/unitcell.cpp.o:
	$(MAKE) -f CMakeFiles/moldycat.dir/build.make CMakeFiles/moldycat.dir/src/sim/unitcell.cpp.o
.PHONY : src/sim/unitcell.cpp.o

src/sim/unitcell.i: src/sim/unitcell.cpp.i
.PHONY : src/sim/unitcell.i

# target to preprocess a source file
src/sim/unitcell.cpp.i:
	$(MAKE) -f CMakeFiles/moldycat.dir/build.make CMakeFiles/moldycat.dir/src/sim/unitcell.cpp.i
.PHONY : src/sim/unitcell.cpp.i

src/sim/unitcell.s: src/sim/unitcell.cpp.s
.PHONY : src/sim/unitcell.s

# target to generate assembly for a file
src/sim/unitcell.cpp.s:
	$(MAKE) -f CMakeFiles/moldycat.dir/build.make CMakeFiles/moldycat.dir/src/sim/unitcell.cpp.s
.PHONY : src/sim/unitcell.cpp.s

src/thermo/andersen.o: src/thermo/andersen.cpp.o
.PHONY : src/thermo/andersen.o

# target to build an object file
src/thermo/andersen.cpp.o:
	$(MAKE) -f CMakeFiles/moldycat.dir/build.make CMakeFiles/moldycat.dir/src/thermo/andersen.cpp.o
.PHONY : src/thermo/andersen.cpp.o

src/thermo/andersen.i: src/thermo/andersen.cpp.i
.PHONY : src/thermo/andersen.i

# target to preprocess a source file
src/thermo/andersen.cpp.i:
	$(MAKE) -f CMakeFiles/moldycat.dir/build.make CMakeFiles/moldycat.dir/src/thermo/andersen.cpp.i
.PHONY : src/thermo/andersen.cpp.i

src/thermo/andersen.s: src/thermo/andersen.cpp.s
.PHONY : src/thermo/andersen.s

# target to generate assembly for a file
src/thermo/andersen.cpp.s:
	$(MAKE) -f CMakeFiles/moldycat.dir/build.make CMakeFiles/moldycat.dir/src/thermo/andersen.cpp.s
.PHONY : src/thermo/andersen.cpp.s

src/thermo/nothermo.o: src/thermo/nothermo.cpp.o
.PHONY : src/thermo/nothermo.o

# target to build an object file
src/thermo/nothermo.cpp.o:
	$(MAKE) -f CMakeFiles/moldycat.dir/build.make CMakeFiles/moldycat.dir/src/thermo/nothermo.cpp.o
.PHONY : src/thermo/nothermo.cpp.o

src/thermo/nothermo.i: src/thermo/nothermo.cpp.i
.PHONY : src/thermo/nothermo.i

# target to preprocess a source file
src/thermo/nothermo.cpp.i:
	$(MAKE) -f CMakeFiles/moldycat.dir/build.make CMakeFiles/moldycat.dir/src/thermo/nothermo.cpp.i
.PHONY : src/thermo/nothermo.cpp.i

src/thermo/nothermo.s: src/thermo/nothermo.cpp.s
.PHONY : src/thermo/nothermo.s

# target to generate assembly for a file
src/thermo/nothermo.cpp.s:
	$(MAKE) -f CMakeFiles/moldycat.dir/build.make CMakeFiles/moldycat.dir/src/thermo/nothermo.cpp.s
.PHONY : src/thermo/nothermo.cpp.s

src/thermo/rand.o: src/thermo/rand.cpp.o
.PHONY : src/thermo/rand.o

# target to build an object file
src/thermo/rand.cpp.o:
	$(MAKE) -f CMakeFiles/moldycat.dir/build.make CMakeFiles/moldycat.dir/src/thermo/rand.cpp.o
.PHONY : src/thermo/rand.cpp.o

src/thermo/rand.i: src/thermo/rand.cpp.i
.PHONY : src/thermo/rand.i

# target to preprocess a source file
src/thermo/rand.cpp.i:
	$(MAKE) -f CMakeFiles/moldycat.dir/build.make CMakeFiles/moldycat.dir/src/thermo/rand.cpp.i
.PHONY : src/thermo/rand.cpp.i

src/thermo/rand.s: src/thermo/rand.cpp.s
.PHONY : src/thermo/rand.s

# target to generate assembly for a file
src/thermo/rand.cpp.s:
	$(MAKE) -f CMakeFiles/moldycat.dir/build.make CMakeFiles/moldycat.dir/src/thermo/rand.cpp.s
.PHONY : src/thermo/rand.cpp.s

src/thermo/thermobase.o: src/thermo/thermobase.cpp.o
.PHONY : src/thermo/thermobase.o

# target to build an object file
src/thermo/thermobase.cpp.o:
	$(MAKE) -f CMakeFiles/moldycat.dir/build.make CMakeFiles/moldycat.dir/src/thermo/thermobase.cpp.o
.PHONY : src/thermo/thermobase.cpp.o

src/thermo/thermobase.i: src/thermo/thermobase.cpp.i
.PHONY : src/thermo/thermobase.i

# target to preprocess a source file
src/thermo/thermobase.cpp.i:
	$(MAKE) -f CMakeFiles/moldycat.dir/build.make CMakeFiles/moldycat.dir/src/thermo/thermobase.cpp.i
.PHONY : src/thermo/thermobase.cpp.i

src/thermo/thermobase.s: src/thermo/thermobase.cpp.s
.PHONY : src/thermo/thermobase.s

# target to generate assembly for a file
src/thermo/thermobase.cpp.s:
	$(MAKE) -f CMakeFiles/moldycat.dir/build.make CMakeFiles/moldycat.dir/src/thermo/thermobase.cpp.s
.PHONY : src/thermo/thermobase.cpp.s

src/thermo/velocityscaler.o: src/thermo/velocityscaler.cpp.o
.PHONY : src/thermo/velocityscaler.o

# target to build an object file
src/thermo/velocityscaler.cpp.o:
	$(MAKE) -f CMakeFiles/moldycat.dir/build.make CMakeFiles/moldycat.dir/src/thermo/velocityscaler.cpp.o
.PHONY : src/thermo/velocityscaler.cpp.o

src/thermo/velocityscaler.i: src/thermo/velocityscaler.cpp.i
.PHONY : src/thermo/velocityscaler.i

# target to preprocess a source file
src/thermo/velocityscaler.cpp.i:
	$(MAKE) -f CMakeFiles/moldycat.dir/build.make CMakeFiles/moldycat.dir/src/thermo/velocityscaler.cpp.i
.PHONY : src/thermo/velocityscaler.cpp.i

src/thermo/velocityscaler.s: src/thermo/velocityscaler.cpp.s
.PHONY : src/thermo/velocityscaler.s

# target to generate assembly for a file
src/thermo/velocityscaler.cpp.s:
	$(MAKE) -f CMakeFiles/moldycat.dir/build.make CMakeFiles/moldycat.dir/src/thermo/velocityscaler.cpp.s
.PHONY : src/thermo/velocityscaler.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... moldycat"
	@echo "... rebuild_cache"
	@echo "... src/atom/atom.o"
	@echo "... src/atom/atom.i"
	@echo "... src/atom/atom.s"
	@echo "... src/atom/vect3.o"
	@echo "... src/atom/vect3.i"
	@echo "... src/atom/vect3.s"
	@echo "... src/moldycat.o"
	@echo "... src/moldycat.i"
	@echo "... src/moldycat.s"
	@echo "... src/sim/unitcell.o"
	@echo "... src/sim/unitcell.i"
	@echo "... src/sim/unitcell.s"
	@echo "... src/thermo/andersen.o"
	@echo "... src/thermo/andersen.i"
	@echo "... src/thermo/andersen.s"
	@echo "... src/thermo/nothermo.o"
	@echo "... src/thermo/nothermo.i"
	@echo "... src/thermo/nothermo.s"
	@echo "... src/thermo/rand.o"
	@echo "... src/thermo/rand.i"
	@echo "... src/thermo/rand.s"
	@echo "... src/thermo/thermobase.o"
	@echo "... src/thermo/thermobase.i"
	@echo "... src/thermo/thermobase.s"
	@echo "... src/thermo/velocityscaler.o"
	@echo "... src/thermo/velocityscaler.i"
	@echo "... src/thermo/velocityscaler.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

